import type { Config } from 'tailwindcss';

const prefixs = [
    'shadow',
    'bg',
    'text',
    'focus:shadow',
    'focus:text',
    'focus:bg',
    'hover:bg',
    'hover:text',
    'hover:shadow',
    'placeholder',
];

const colors = [
    'burgundy',
    'champagne',
    'marfil',
    'purewhite',
    'copper',
    'gold',
    'greygrey',
    'greydark',
];

const safelist = [];
for (const color of colors) {
    for (const prefix of prefixs) {
        safelist.push(`${prefix}-${color}`);
        safelist.push(`${prefix}-${color}light`);
    }
}

const shadow = '0 0 12px ';
const config: Config = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--background)',
                foreground: 'var(--foreground)',
                burgundy: '#800020',
                burgunlight: '#aa0030',
                champagne: '#f7e7ce',
                copper: '#b87333',
                greygrey: '#333333',
                greydark: '#222222',
                gold: '#d4af37',
                marfil: '#faf3e0',
                purewhite: '#fafafa',
                burgundylight: '#9b2a45',
                champagnelight: '#f9f0d3',
                copperlight: '#d8915d',
                greygreylight: '#4d4d4d',
                greydarklight: '#404040',
                goldlight: '#e4c26a',
                marfillight: '#fdf7e3',
                purewhitelight: '#ffffff',
            },
            boxShadow: {
                burgundy: shadow + '#800020',
                burgunlight: shadow + '#aa0030',
                champagne: shadow + '#f7e7ce',
                copper: shadow + '#b87333',
                greygrey: shadow + '#333333',
                greydark: shadow + '#222222',
                gold: shadow + '#d4af37',
                marfil: shadow + '#faf3e0',
                purewhite: shadow + '#fafafa',
            },
        },
    },
    safelist: [
        'bg-burgundy',
        'bg-gold',
        'bg-copper',
        'bg-greygrey',
        'bg-greydark',
        'bg-marfil',
        'bg-purewhite',
        'bg-champagelight',
        'bg-burgundylight',
        'bg-goldlight',
        'bg-copperlight',
        'bg-greygreylight',
        'bg-greydarklight',
        'bg-marfillight',
        'bg-purewhitelight',
        'bg-champagelight',
        //hover bg
        'hover:bg-burgundy',
        'hover:bg-gold',
        'hover:bg-copper',
        'hover:bg-greygrey',
        'hover:bg-greydark',
        'hover:bg-marfil',
        'hover:bg-purewhite',
        'hover:bg-champagelight',
        'hover:bg-burgundylight',
        'hover:bg-goldlight',
        'hover:bg-copperlight',
        'hover:bg-greygreylight',
        'hover:bg-greydarklight',
        'hover:bg-marfillight',
        'hover:bg-purewhitelight',
        'hover:bg-champagelight',
        //bg text
        'hover:text-burgundy',
        'hover:text-gold',
        'hover:text-copper',
        'hover:text-greygrey',
        'hover:text-greydark',
        'hover:text-marfil',
        'hover:text-purewhite',
        'hover:text-champagelight',
        'hover:text-burgundylight',
        'hover:text-goldlight',
        'hover:text-copperlight',
        'hover:text-greygreylight',
        'hover:text-greydarklight',
        'hover:text-marfillight',
        'hover:text-purewhitelight',
        'hover:text-champagelight',
        //placeholders
        'placeholder-burgundy',
        'placeholder-gold',
        'placeholder-copper',
        'placeholder-greygrey',
        'placeholder-greydark',
        'placeholder-marfil',
        'placeholder-purewhite',
        'placeholder-champagelight',
        'placeholder-burgundylight',
        'placeholder-goldlight',
        'placeholder-copperlight',
        'placeholder-greygreylight',
        'placeholder-greydarklight',
        'placeholder-marfillight',
        'placeholder-purewhitelight',
        'placeholder-champagelight',
        //borders
        'border-burgundy',
        'border-gold',
        'border-copper',
        'border-greygrey',
        'border-greydark',
        'border-marfil',
        'border-purewhite',
        'border-champagelight',
        'border-burgundylight',
        'border-goldlight',
        'border-copperlight',
        'border-greygreylight',
        'border-greydarklight',
        'border-marfillight',
        'border-purewhitelight',
        'border-champagelight',
        //Texts
        'text-burgundy',
        'text-gold',
        'text-copper',
        'text-greygrey',
        'text-greydark',
        'text-marfil',
        'text-purewhite',
        'text-champagelight',
        'text-burgundylight',
        'text-goldlight',
        'text-copperlight',
        'text-greygreylight',
        'text-greydarklight',
        'text-marfillight',
        'text-purewhitelight',
        'text-champagelight',
        //shadows
        'shadow-burgundy',
        'shadow-gold',
        'shadow-copper',
        'shadow-greygrey',
        'shadow-greydark',
        'shadow-marfil',
        'shadow-purewhite',
        'shadow-champagelight',
        'shadow-burgundylight',
        'shadow-goldlight',
        'shadow-copperlight',
        'shadow-greygreylight',
        'shadow-greydarklight',
        'shadow-marfillight',
        'shadow-purewhitelight',
        'shadow-champagelight',
        //focus shadow
        'focus:shadow-burgundy',
        'focus:shadow-gold',
        'focus:shadow-copper',
        'focus:shadow-greygrey',
        'focus:shadow-greydark',
        'focus:shadow-marfil',
        'focus:shadow-purewhite',
        'focus:shadow-champagelight',
        'focus:shadow-burgundylight',
        'focus:shadow-goldlight',
        'focus:shadow-copperlight',
        'focus:shadow-greygreylight',
        'focus:shadow-greydarklight',
        'focus:shadow-marfillight',
        'focus:shadow-purewhitelight',
        'focus:shadow-champagelight',
    ],
    plugins: [],
};
export default config;
